#!/usr/bin/python3

# Example flask application for containerization
#
# Copyright (C) 2021 Bruce Ashfield <bruce.ashfield@gmail.com>
# License: MIT (see COPYING.MIT at the root of the repository for terms)

from flask import Flask

app = Flask(__name__)

@app.route('/embarcados/', methods=['GET', 'POST'])
def welcome():
    return "Hello from Embarcados!\n"

@app.route('/emclogic/', methods=['GET', 'POST'])
def welcomeemc():
    return "Hello from Emc Logic!\n"

@app.route('/linux/', methods=['GET', 'POST'])
def welcomeseminario():
    return "Hello from Seminario Linux Embarcado 2026!\n"

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=9000)
